In [1]:
from __future__ import print_function
import torch

### How to create TENSORS

In [2]:
# Uninitialized matrix
x = torch.empty(5, 3)
x

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])

In [3]:
# Randomly initialized matrix
x = torch.rand(5, 3)
x

tensor([[0.6711, 0.4342, 0.8042],
        [0.4084, 0.5102, 0.5481],
        [0.7000, 0.5522, 0.6118],
        [0.6968, 0.0023, 0.2695],
        [0.2409, 0.1177, 0.5703]])

In [5]:
# Filled with zeros
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
# Directly from data
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [7]:
# Creating tensors based on existing ones
x = x.new_ones(5, 3, dtype=torch.double)  # new_*** is a method of tensor()
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1556,  1.0510, -0.1043],
        [-1.8056,  0.7623, -1.3833],
        [-0.7889,  3.0313,  0.9229],
        [ 1.2218,  0.4913,  0.1038],
        [ 0.5949, -0.7122,  2.0500]])


### Tensor Operations

In [10]:
y = torch.randn_like(x)
y

tensor([[ 0.5260,  1.7898,  0.5999],
        [ 0.3311,  1.3143, -0.1241],
        [ 1.1161, -0.0743, -0.8371],
        [-0.3529, -0.8255, -0.9472],
        [ 0.0166, -0.5324,  1.1672]])

In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3704,  2.8408,  0.4956],
        [-1.4745,  2.0767, -1.5074],
        [ 0.3272,  2.9570,  0.0858],
        [ 0.8689, -0.3342, -0.8434],
        [ 0.6115, -1.2447,  3.2172]])


In [12]:
# In-place Operation
y.add_(x)
y

tensor([[ 0.3704,  2.8408,  0.4956],
        [-1.4745,  2.0767, -1.5074],
        [ 0.3272,  2.9570,  0.0858],
        [ 0.8689, -0.3342, -0.8434],
        [ 0.6115, -1.2447,  3.2172]])

In [15]:
print(x)
print(x[:, 1])
print(x[:, [1]])

tensor([[-0.1556,  1.0510, -0.1043],
        [-1.8056,  0.7623, -1.3833],
        [-0.7889,  3.0313,  0.9229],
        [ 1.2218,  0.4913,  0.1038],
        [ 0.5949, -0.7122,  2.0500]])
tensor([ 1.0510,  0.7623,  3.0313,  0.4913, -0.7122])
tensor([[ 1.0510],
        [ 0.7623],
        [ 3.0313],
        [ 0.4913],
        [-0.7122]])


In [16]:
# Reshaping: view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# Extract a 0-d scala
x = torch.randn(1)
print(type(x))
print(type(x.item()))

<class 'torch.Tensor'>
<class 'float'>
